version: '3'
services:
  golf-club-api:
    image: golf-club-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_club_db
      #- spring.datasource.url=jdbc:mysql://your-rds-endpoint.us-east-1.rds.amazonaws.com/golf_club_db
      - spring.datasource.password=password
      - spring.datasource.username=root
